mysql:
  user: "root"
  password: "123"
  host: "172.25.13.23"
  port: 3306
  database: "jyu"
  charset: "utf8"
  parseTime: true
  loc: "Local"

redis:
  addr: "127.0.0.1:6379"
  password: ""
  DB: 0
  poolSize: 128
  minIdleConn: 30
